### PR TITLE
Add reference to OpenUICG Popup API

### PR DESCRIPTION
**Pull request by Westbrook**
ARIA Attributes _might_ not be the only ones we want to reflect here...

### CODE REVIEW

**Comment by mrego** [comment]
Would also make sense to add an example related to `<label for=input>`?

For example if we have:
```html
<x-label>
  <template shadowroot="open">
    <label id="mylabel1" for="myinput1">my label 1</label>
  </template>
</x-label>
<input id="myinput1" />
```

The relationship is not going to be set (because [HTML spec mention they should be in the same tree](https://html.spec.whatwg.org/multipage/forms.html#attr-label-for)). But also `myinput1.labels` won't have access to the things inside the shadow tree.


Or the other way around:
```html
<label id="mylabel2" for="myinput2">my label 2</label>
<x-input>
  <template shadowroot="open">
    <input id="myinput2" />
  </template>
</x-input>
```

More discussion on label-input relationship at https://github.com/whatwg/html/issues/3219.

**Comment by Westbrook** [comment]
@mrego checkout https://github.com/Westbrook/cross-root-aria-reflection/pull/3 where there is some of that.

**Comment by nolanlawson** [comment]
Hm, if we support popups, wouldn't we arguably want to support dialogs (e.g. the `open` attribute), details/summary (also an `open` attribute), etc.? Seems useful, but could get hairy. Maybe could be handled in a v2 of this API? 🙂

**Comment by mrego** [comment]
> Hm, if we support popups, wouldn't we arguably want to support dialogs (e.g. the `open` attribute), details/summary (also an `open` attribute), etc.? Seems useful, but could get hairy. Maybe could be handled in a v2 of this API? slightly_smiling_face

Not sure if I got what you mean by the `open` attribute, that attribute doesn't reference an element, it's a boolean one.

In the [OpenUI popup proposal](https://open-ui.org/components/popup.research.explainer) there are attributes like `togglepopup`, `showpopup`, and `hidepopup`; that point to another element (that element could be in a Shadow DOM and then reflection might be useful).

Is there anything similar with details/summary or dialog?

**Comment by nolanlawson** [comment]
Ah, my mistake; you're right! No, I can't think of any other element-referencing attributes.

**Comment by Westbrook** [comment]
I should also add reference back to the `anchor` attribute here, too.

**Pull request merged**
